### ISSUE TITLE
mainnet checklist

### ISSUE THREAD

**Issue by ross-weir** [ross-weir/Donera#88]
**Contracts**

- [ ] Determine fee structure
- [ ] Do a test run through of upgrading contracts/add test for upgrade scenarios
- [ ] Add tests for all privlidged contract actions
- [ ] **nice-to-have** move some fields to ipfs (allow for longer descriptions, reduce onchain state, etc) - will need to do this but can come later
